class Food < ActiveRecord::Base

  USDA_ABBRIV_FIELDS = {
    ndb_number: :string,
    short_desc: :string,
    water: :decimal,
    kcal: :decimal,
    protein: :decimal,
    total_fat: :decimal,
    ash: :decimal,
    carbs: :decimal,
    total_fiber: :decimal,
    sugar: :decimal,
    calcium: :decimal,
    iron: :decimal,
    magnesium: :decimal,
    phosphorus: :decimal,
    sodium: :decimal,
    zinc: :decimal,
    copper: :decimal,
    manganese: :decimal,
    selenium: :decimal,
    vitamin_c: :decimal,
    thiamin: :decimal,
    riboflavin: :decimal,
    niacin: :decimal,
    panto_acid: :decimal,
    vitamin_b6: :decimal,
    total_folate: :decimal,
    folic_acid: :decimal,
    food_folate: :decimal,
    folate: :decimal,
    choline: :decimal,
    vitamin_b12: :decimal,
    vitamin_a_iu: :decimal,
    vitamin_a_rae: :decimal,
    retinol: :decimal,
    alpha_carot: :decimal,
    beta_carot: :decimal,
    lycopene: :decimal,
    lutein: :decimal,
    vitamin_e: :decimal,
    vitamin_d_mcg: :decimal,
    vitamin_d_iu: :decimal,
    vitamin_k: :decimal,
    saturated_fat: :decimal,
    monounsaturated_fat: :decimal,
    polyunsaturated_fat: :decimal,
    cholesterol: :decimal,
    weight_1_grams: :decimal,
    weight_1_desc: :string,
    weight_2_grams: :decimal,
    weight_2_desc: :string,
    refuse_percent: :decimal
  }

end
